/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as marketingMarketingLayoutRouteImport } from './routes/(marketing)/_marketing-layout'
import { Route as authAuthLayoutRouteImport } from './routes/(auth)/_auth-layout'
import { Route as marketingMarketingLayoutIndexRouteImport } from './routes/(marketing)/_marketing-layout/index'
import { Route as marketingMarketingLayoutSlugRouteImport } from './routes/(marketing)/_marketing-layout/$slug'
import { Route as marketingMarketingLayoutPricingIndexRouteImport } from './routes/(marketing)/_marketing-layout/pricing/index'
import { Route as marketingMarketingLayoutBlogIndexRouteImport } from './routes/(marketing)/_marketing-layout/blog/index'
import { Route as authAuthLayoutRegisterIndexRouteImport } from './routes/(auth)/_auth-layout/register/index'
import { Route as authAuthLayoutLoginIndexRouteImport } from './routes/(auth)/_auth-layout/login/index'
import { Route as marketingMarketingLayoutBlogSlugRouteImport } from './routes/(marketing)/_marketing-layout/blog/$slug'

const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingMarketingLayoutRoute =
  marketingMarketingLayoutRouteImport.update({
    id: '/(marketing)/_marketing-layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const authAuthLayoutRoute = authAuthLayoutRouteImport.update({
  id: '/(auth)/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingMarketingLayoutIndexRoute =
  marketingMarketingLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => marketingMarketingLayoutRoute,
  } as any)
const marketingMarketingLayoutSlugRoute =
  marketingMarketingLayoutSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => marketingMarketingLayoutRoute,
  } as any)
const marketingMarketingLayoutPricingIndexRoute =
  marketingMarketingLayoutPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => marketingMarketingLayoutRoute,
  } as any)
const marketingMarketingLayoutBlogIndexRoute =
  marketingMarketingLayoutBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => marketingMarketingLayoutRoute,
  } as any)
const authAuthLayoutRegisterIndexRoute =
  authAuthLayoutRegisterIndexRouteImport.update({
    id: '/register/',
    path: '/register/',
    getParentRoute: () => authAuthLayoutRoute,
  } as any)
const authAuthLayoutLoginIndexRoute =
  authAuthLayoutLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => authAuthLayoutRoute,
  } as any)
const marketingMarketingLayoutBlogSlugRoute =
  marketingMarketingLayoutBlogSlugRouteImport.update({
    id: '/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => marketingMarketingLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/api/og': typeof ApiOgRoute
  '/$slug': typeof marketingMarketingLayoutSlugRoute
  '/': typeof marketingMarketingLayoutIndexRoute
  '/blog/$slug': typeof marketingMarketingLayoutBlogSlugRoute
  '/login': typeof authAuthLayoutLoginIndexRoute
  '/register': typeof authAuthLayoutRegisterIndexRoute
  '/blog': typeof marketingMarketingLayoutBlogIndexRoute
  '/pricing': typeof marketingMarketingLayoutPricingIndexRoute
}
export interface FileRoutesByTo {
  '/api/og': typeof ApiOgRoute
  '/$slug': typeof marketingMarketingLayoutSlugRoute
  '/': typeof marketingMarketingLayoutIndexRoute
  '/blog/$slug': typeof marketingMarketingLayoutBlogSlugRoute
  '/login': typeof authAuthLayoutLoginIndexRoute
  '/register': typeof authAuthLayoutRegisterIndexRoute
  '/blog': typeof marketingMarketingLayoutBlogIndexRoute
  '/pricing': typeof marketingMarketingLayoutPricingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_auth-layout': typeof authAuthLayoutRouteWithChildren
  '/(marketing)/_marketing-layout': typeof marketingMarketingLayoutRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/(marketing)/_marketing-layout/$slug': typeof marketingMarketingLayoutSlugRoute
  '/(marketing)/_marketing-layout/': typeof marketingMarketingLayoutIndexRoute
  '/(marketing)/_marketing-layout/blog/$slug': typeof marketingMarketingLayoutBlogSlugRoute
  '/(auth)/_auth-layout/login/': typeof authAuthLayoutLoginIndexRoute
  '/(auth)/_auth-layout/register/': typeof authAuthLayoutRegisterIndexRoute
  '/(marketing)/_marketing-layout/blog/': typeof marketingMarketingLayoutBlogIndexRoute
  '/(marketing)/_marketing-layout/pricing/': typeof marketingMarketingLayoutPricingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/og'
    | '/$slug'
    | '/'
    | '/blog/$slug'
    | '/login'
    | '/register'
    | '/blog'
    | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/og'
    | '/$slug'
    | '/'
    | '/blog/$slug'
    | '/login'
    | '/register'
    | '/blog'
    | '/pricing'
  id:
    | '__root__'
    | '/(auth)/_auth-layout'
    | '/(marketing)/_marketing-layout'
    | '/api/og'
    | '/(marketing)/_marketing-layout/$slug'
    | '/(marketing)/_marketing-layout/'
    | '/(marketing)/_marketing-layout/blog/$slug'
    | '/(auth)/_auth-layout/login/'
    | '/(auth)/_auth-layout/register/'
    | '/(marketing)/_marketing-layout/blog/'
    | '/(marketing)/_marketing-layout/pricing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAuthLayoutRoute: typeof authAuthLayoutRouteWithChildren
  marketingMarketingLayoutRoute: typeof marketingMarketingLayoutRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/_marketing-layout': {
      id: '/(marketing)/_marketing-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingMarketingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth-layout': {
      id: '/(auth)/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/_marketing-layout/': {
      id: '/(marketing)/_marketing-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingMarketingLayoutIndexRouteImport
      parentRoute: typeof marketingMarketingLayoutRoute
    }
    '/(marketing)/_marketing-layout/$slug': {
      id: '/(marketing)/_marketing-layout/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof marketingMarketingLayoutSlugRouteImport
      parentRoute: typeof marketingMarketingLayoutRoute
    }
    '/(marketing)/_marketing-layout/pricing/': {
      id: '/(marketing)/_marketing-layout/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof marketingMarketingLayoutPricingIndexRouteImport
      parentRoute: typeof marketingMarketingLayoutRoute
    }
    '/(marketing)/_marketing-layout/blog/': {
      id: '/(marketing)/_marketing-layout/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof marketingMarketingLayoutBlogIndexRouteImport
      parentRoute: typeof marketingMarketingLayoutRoute
    }
    '/(auth)/_auth-layout/register/': {
      id: '/(auth)/_auth-layout/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authAuthLayoutRegisterIndexRouteImport
      parentRoute: typeof authAuthLayoutRoute
    }
    '/(auth)/_auth-layout/login/': {
      id: '/(auth)/_auth-layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLayoutLoginIndexRouteImport
      parentRoute: typeof authAuthLayoutRoute
    }
    '/(marketing)/_marketing-layout/blog/$slug': {
      id: '/(marketing)/_marketing-layout/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof marketingMarketingLayoutBlogSlugRouteImport
      parentRoute: typeof marketingMarketingLayoutRoute
    }
  }
}

interface authAuthLayoutRouteChildren {
  authAuthLayoutLoginIndexRoute: typeof authAuthLayoutLoginIndexRoute
  authAuthLayoutRegisterIndexRoute: typeof authAuthLayoutRegisterIndexRoute
}

const authAuthLayoutRouteChildren: authAuthLayoutRouteChildren = {
  authAuthLayoutLoginIndexRoute: authAuthLayoutLoginIndexRoute,
  authAuthLayoutRegisterIndexRoute: authAuthLayoutRegisterIndexRoute,
}

const authAuthLayoutRouteWithChildren = authAuthLayoutRoute._addFileChildren(
  authAuthLayoutRouteChildren,
)

interface marketingMarketingLayoutRouteChildren {
  marketingMarketingLayoutSlugRoute: typeof marketingMarketingLayoutSlugRoute
  marketingMarketingLayoutIndexRoute: typeof marketingMarketingLayoutIndexRoute
  marketingMarketingLayoutBlogSlugRoute: typeof marketingMarketingLayoutBlogSlugRoute
  marketingMarketingLayoutBlogIndexRoute: typeof marketingMarketingLayoutBlogIndexRoute
  marketingMarketingLayoutPricingIndexRoute: typeof marketingMarketingLayoutPricingIndexRoute
}

const marketingMarketingLayoutRouteChildren: marketingMarketingLayoutRouteChildren =
  {
    marketingMarketingLayoutSlugRoute: marketingMarketingLayoutSlugRoute,
    marketingMarketingLayoutIndexRoute: marketingMarketingLayoutIndexRoute,
    marketingMarketingLayoutBlogSlugRoute:
      marketingMarketingLayoutBlogSlugRoute,
    marketingMarketingLayoutBlogIndexRoute:
      marketingMarketingLayoutBlogIndexRoute,
    marketingMarketingLayoutPricingIndexRoute:
      marketingMarketingLayoutPricingIndexRoute,
  }

const marketingMarketingLayoutRouteWithChildren =
  marketingMarketingLayoutRoute._addFileChildren(
    marketingMarketingLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authAuthLayoutRoute: authAuthLayoutRouteWithChildren,
  marketingMarketingLayoutRoute: marketingMarketingLayoutRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
