/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as marketingMarketingLayoutRouteImport } from './routes/(marketing)/_marketing-layout'
import { Route as editorEditorLayoutRouteImport } from './routes/(editor)/_editor-layout'
import { Route as docsDocsLayoutRouteImport } from './routes/(docs)/_docs-layout'
import { Route as authAuthLayoutRouteImport } from './routes/(auth)/_auth-layout'
import { Route as marketingMarketingLayoutIndexRouteImport } from './routes/(marketing)/_marketing-layout/index'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as marketingMarketingLayoutSlugRouteImport } from './routes/(marketing)/_marketing-layout/$slug'
import { Route as dashboardDashboardDashboardLayoutRouteImport } from './routes/(dashboard)/dashboard/_dashboard-layout'
import { Route as marketingMarketingLayoutPricingIndexRouteImport } from './routes/(marketing)/_marketing-layout/pricing/index'
import { Route as marketingMarketingLayoutBlogIndexRouteImport } from './routes/(marketing)/_marketing-layout/blog/index'
import { Route as docsDocsLayoutGuidesIndexRouteImport } from './routes/(docs)/_docs-layout/guides/index'
import { Route as dashboardDashboardDashboardLayoutIndexRouteImport } from './routes/(dashboard)/dashboard/_dashboard-layout/index'
import { Route as authAuthLayoutRegisterIndexRouteImport } from './routes/(auth)/_auth-layout/register/index'
import { Route as authAuthLayoutLoginIndexRouteImport } from './routes/(auth)/_auth-layout/login/index'
import { Route as marketingMarketingLayoutBlogSlugRouteImport } from './routes/(marketing)/_marketing-layout/blog/$slug'
import { Route as editorEditorLayoutEditorPostIdRouteImport } from './routes/(editor)/_editor-layout/editor/$postId'
import { Route as docsDocsLayoutDocsLayoutRouteImport } from './routes/(docs)/_docs-layout/docs/_layout'
import { Route as docsDocsLayoutDocsLayoutIndexRouteImport } from './routes/(docs)/_docs-layout/docs/_layout.index'
import { Route as dashboardDashboardDashboardLayoutSettingsIndexRouteImport } from './routes/(dashboard)/dashboard/_dashboard-layout/settings/index'
import { Route as dashboardDashboardDashboardLayoutBillingIndexRouteImport } from './routes/(dashboard)/dashboard/_dashboard-layout/billing/index'
import { Route as docsDocsLayoutDocsLayoutSplatRouteImport } from './routes/(docs)/_docs-layout/docs/_layout.$'

const dashboardDashboardRouteImport = createFileRoute(
  '/(dashboard)/dashboard',
)()
const docsDocsLayoutDocsRouteImport = createFileRoute(
  '/(docs)/_docs-layout/docs',
)()

const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingMarketingLayoutRoute =
  marketingMarketingLayoutRouteImport.update({
    id: '/(marketing)/_marketing-layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const editorEditorLayoutRoute = editorEditorLayoutRouteImport.update({
  id: '/(editor)/_editor-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const docsDocsLayoutRoute = docsDocsLayoutRouteImport.update({
  id: '/(docs)/_docs-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthLayoutRoute = authAuthLayoutRouteImport.update({
  id: '/(auth)/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const docsDocsLayoutDocsRoute = docsDocsLayoutDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => docsDocsLayoutRoute,
} as any)
const marketingMarketingLayoutIndexRoute =
  marketingMarketingLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => marketingMarketingLayoutRoute,
  } as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingMarketingLayoutSlugRoute =
  marketingMarketingLayoutSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => marketingMarketingLayoutRoute,
  } as any)
const dashboardDashboardDashboardLayoutRoute =
  dashboardDashboardDashboardLayoutRouteImport.update({
    id: '/_dashboard-layout',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const marketingMarketingLayoutPricingIndexRoute =
  marketingMarketingLayoutPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => marketingMarketingLayoutRoute,
  } as any)
const marketingMarketingLayoutBlogIndexRoute =
  marketingMarketingLayoutBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => marketingMarketingLayoutRoute,
  } as any)
const docsDocsLayoutGuidesIndexRoute =
  docsDocsLayoutGuidesIndexRouteImport.update({
    id: '/guides/',
    path: '/guides/',
    getParentRoute: () => docsDocsLayoutRoute,
  } as any)
const dashboardDashboardDashboardLayoutIndexRoute =
  dashboardDashboardDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => dashboardDashboardDashboardLayoutRoute,
  } as any)
const authAuthLayoutRegisterIndexRoute =
  authAuthLayoutRegisterIndexRouteImport.update({
    id: '/register/',
    path: '/register/',
    getParentRoute: () => authAuthLayoutRoute,
  } as any)
const authAuthLayoutLoginIndexRoute =
  authAuthLayoutLoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => authAuthLayoutRoute,
  } as any)
const marketingMarketingLayoutBlogSlugRoute =
  marketingMarketingLayoutBlogSlugRouteImport.update({
    id: '/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => marketingMarketingLayoutRoute,
  } as any)
const editorEditorLayoutEditorPostIdRoute =
  editorEditorLayoutEditorPostIdRouteImport.update({
    id: '/editor/$postId',
    path: '/editor/$postId',
    getParentRoute: () => editorEditorLayoutRoute,
  } as any)
const docsDocsLayoutDocsLayoutRoute =
  docsDocsLayoutDocsLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => docsDocsLayoutDocsRoute,
  } as any)
const docsDocsLayoutDocsLayoutIndexRoute =
  docsDocsLayoutDocsLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => docsDocsLayoutDocsLayoutRoute,
  } as any)
const dashboardDashboardDashboardLayoutSettingsIndexRoute =
  dashboardDashboardDashboardLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => dashboardDashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardDashboardLayoutBillingIndexRoute =
  dashboardDashboardDashboardLayoutBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => dashboardDashboardDashboardLayoutRoute,
  } as any)
const docsDocsLayoutDocsLayoutSplatRoute =
  docsDocsLayoutDocsLayoutSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => docsDocsLayoutDocsLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/api/og': typeof ApiOgRoute
  '/dashboard': typeof dashboardDashboardDashboardLayoutRouteWithChildren
  '/$slug': typeof marketingMarketingLayoutSlugRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/': typeof marketingMarketingLayoutIndexRoute
  '/docs': typeof docsDocsLayoutDocsLayoutRouteWithChildren
  '/editor/$postId': typeof editorEditorLayoutEditorPostIdRoute
  '/blog/$slug': typeof marketingMarketingLayoutBlogSlugRoute
  '/login': typeof authAuthLayoutLoginIndexRoute
  '/register': typeof authAuthLayoutRegisterIndexRoute
  '/dashboard/': typeof dashboardDashboardDashboardLayoutIndexRoute
  '/guides': typeof docsDocsLayoutGuidesIndexRoute
  '/blog': typeof marketingMarketingLayoutBlogIndexRoute
  '/pricing': typeof marketingMarketingLayoutPricingIndexRoute
  '/docs/$': typeof docsDocsLayoutDocsLayoutSplatRoute
  '/dashboard/billing': typeof dashboardDashboardDashboardLayoutBillingIndexRoute
  '/dashboard/settings': typeof dashboardDashboardDashboardLayoutSettingsIndexRoute
  '/docs/': typeof docsDocsLayoutDocsLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/api/og': typeof ApiOgRoute
  '/dashboard': typeof dashboardDashboardDashboardLayoutIndexRoute
  '/$slug': typeof marketingMarketingLayoutSlugRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/': typeof marketingMarketingLayoutIndexRoute
  '/docs': typeof docsDocsLayoutDocsLayoutIndexRoute
  '/editor/$postId': typeof editorEditorLayoutEditorPostIdRoute
  '/blog/$slug': typeof marketingMarketingLayoutBlogSlugRoute
  '/login': typeof authAuthLayoutLoginIndexRoute
  '/register': typeof authAuthLayoutRegisterIndexRoute
  '/guides': typeof docsDocsLayoutGuidesIndexRoute
  '/blog': typeof marketingMarketingLayoutBlogIndexRoute
  '/pricing': typeof marketingMarketingLayoutPricingIndexRoute
  '/docs/$': typeof docsDocsLayoutDocsLayoutSplatRoute
  '/dashboard/billing': typeof dashboardDashboardDashboardLayoutBillingIndexRoute
  '/dashboard/settings': typeof dashboardDashboardDashboardLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/_auth-layout': typeof authAuthLayoutRouteWithChildren
  '/(docs)/_docs-layout': typeof docsDocsLayoutRouteWithChildren
  '/(editor)/_editor-layout': typeof editorEditorLayoutRouteWithChildren
  '/(marketing)/_marketing-layout': typeof marketingMarketingLayoutRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRouteWithChildren
  '/(dashboard)/dashboard/_dashboard-layout': typeof dashboardDashboardDashboardLayoutRouteWithChildren
  '/(marketing)/_marketing-layout/$slug': typeof marketingMarketingLayoutSlugRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/(marketing)/_marketing-layout/': typeof marketingMarketingLayoutIndexRoute
  '/(docs)/_docs-layout/docs': typeof docsDocsLayoutDocsRouteWithChildren
  '/(docs)/_docs-layout/docs/_layout': typeof docsDocsLayoutDocsLayoutRouteWithChildren
  '/(editor)/_editor-layout/editor/$postId': typeof editorEditorLayoutEditorPostIdRoute
  '/(marketing)/_marketing-layout/blog/$slug': typeof marketingMarketingLayoutBlogSlugRoute
  '/(auth)/_auth-layout/login/': typeof authAuthLayoutLoginIndexRoute
  '/(auth)/_auth-layout/register/': typeof authAuthLayoutRegisterIndexRoute
  '/(dashboard)/dashboard/_dashboard-layout/': typeof dashboardDashboardDashboardLayoutIndexRoute
  '/(docs)/_docs-layout/guides/': typeof docsDocsLayoutGuidesIndexRoute
  '/(marketing)/_marketing-layout/blog/': typeof marketingMarketingLayoutBlogIndexRoute
  '/(marketing)/_marketing-layout/pricing/': typeof marketingMarketingLayoutPricingIndexRoute
  '/(docs)/_docs-layout/docs/_layout/$': typeof docsDocsLayoutDocsLayoutSplatRoute
  '/(dashboard)/dashboard/_dashboard-layout/billing/': typeof dashboardDashboardDashboardLayoutBillingIndexRoute
  '/(dashboard)/dashboard/_dashboard-layout/settings/': typeof dashboardDashboardDashboardLayoutSettingsIndexRoute
  '/(docs)/_docs-layout/docs/_layout/': typeof docsDocsLayoutDocsLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/og'
    | '/dashboard'
    | '/$slug'
    | '/api/webhooks/stripe'
    | '/'
    | '/docs'
    | '/editor/$postId'
    | '/blog/$slug'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/guides'
    | '/blog'
    | '/pricing'
    | '/docs/$'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/og'
    | '/dashboard'
    | '/$slug'
    | '/api/webhooks/stripe'
    | '/'
    | '/docs'
    | '/editor/$postId'
    | '/blog/$slug'
    | '/login'
    | '/register'
    | '/guides'
    | '/blog'
    | '/pricing'
    | '/docs/$'
    | '/dashboard/billing'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/(auth)/_auth-layout'
    | '/(docs)/_docs-layout'
    | '/(editor)/_editor-layout'
    | '/(marketing)/_marketing-layout'
    | '/api/og'
    | '/(dashboard)/dashboard'
    | '/(dashboard)/dashboard/_dashboard-layout'
    | '/(marketing)/_marketing-layout/$slug'
    | '/api/webhooks/stripe'
    | '/(marketing)/_marketing-layout/'
    | '/(docs)/_docs-layout/docs'
    | '/(docs)/_docs-layout/docs/_layout'
    | '/(editor)/_editor-layout/editor/$postId'
    | '/(marketing)/_marketing-layout/blog/$slug'
    | '/(auth)/_auth-layout/login/'
    | '/(auth)/_auth-layout/register/'
    | '/(dashboard)/dashboard/_dashboard-layout/'
    | '/(docs)/_docs-layout/guides/'
    | '/(marketing)/_marketing-layout/blog/'
    | '/(marketing)/_marketing-layout/pricing/'
    | '/(docs)/_docs-layout/docs/_layout/$'
    | '/(dashboard)/dashboard/_dashboard-layout/billing/'
    | '/(dashboard)/dashboard/_dashboard-layout/settings/'
    | '/(docs)/_docs-layout/docs/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authAuthLayoutRoute: typeof authAuthLayoutRouteWithChildren
  docsDocsLayoutRoute: typeof docsDocsLayoutRouteWithChildren
  editorEditorLayoutRoute: typeof editorEditorLayoutRouteWithChildren
  marketingMarketingLayoutRoute: typeof marketingMarketingLayoutRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/_marketing-layout': {
      id: '/(marketing)/_marketing-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingMarketingLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(editor)/_editor-layout': {
      id: '/(editor)/_editor-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof editorEditorLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(docs)/_docs-layout': {
      id: '/(docs)/_docs-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof docsDocsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/_auth-layout': {
      id: '/(auth)/_auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(docs)/_docs-layout/docs': {
      id: '/(docs)/_docs-layout/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof docsDocsLayoutDocsRouteImport
      parentRoute: typeof docsDocsLayoutRoute
    }
    '/(marketing)/_marketing-layout/': {
      id: '/(marketing)/_marketing-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingMarketingLayoutIndexRouteImport
      parentRoute: typeof marketingMarketingLayoutRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/_marketing-layout/$slug': {
      id: '/(marketing)/_marketing-layout/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof marketingMarketingLayoutSlugRouteImport
      parentRoute: typeof marketingMarketingLayoutRoute
    }
    '/(dashboard)/dashboard/_dashboard-layout': {
      id: '/(dashboard)/dashboard/_dashboard-layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardDashboardLayoutRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(marketing)/_marketing-layout/pricing/': {
      id: '/(marketing)/_marketing-layout/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof marketingMarketingLayoutPricingIndexRouteImport
      parentRoute: typeof marketingMarketingLayoutRoute
    }
    '/(marketing)/_marketing-layout/blog/': {
      id: '/(marketing)/_marketing-layout/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof marketingMarketingLayoutBlogIndexRouteImport
      parentRoute: typeof marketingMarketingLayoutRoute
    }
    '/(docs)/_docs-layout/guides/': {
      id: '/(docs)/_docs-layout/guides/'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof docsDocsLayoutGuidesIndexRouteImport
      parentRoute: typeof docsDocsLayoutRoute
    }
    '/(dashboard)/dashboard/_dashboard-layout/': {
      id: '/(dashboard)/dashboard/_dashboard-layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardDashboardDashboardLayoutIndexRouteImport
      parentRoute: typeof dashboardDashboardDashboardLayoutRoute
    }
    '/(auth)/_auth-layout/register/': {
      id: '/(auth)/_auth-layout/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authAuthLayoutRegisterIndexRouteImport
      parentRoute: typeof authAuthLayoutRoute
    }
    '/(auth)/_auth-layout/login/': {
      id: '/(auth)/_auth-layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authAuthLayoutLoginIndexRouteImport
      parentRoute: typeof authAuthLayoutRoute
    }
    '/(marketing)/_marketing-layout/blog/$slug': {
      id: '/(marketing)/_marketing-layout/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof marketingMarketingLayoutBlogSlugRouteImport
      parentRoute: typeof marketingMarketingLayoutRoute
    }
    '/(editor)/_editor-layout/editor/$postId': {
      id: '/(editor)/_editor-layout/editor/$postId'
      path: '/editor/$postId'
      fullPath: '/editor/$postId'
      preLoaderRoute: typeof editorEditorLayoutEditorPostIdRouteImport
      parentRoute: typeof editorEditorLayoutRoute
    }
    '/(docs)/_docs-layout/docs/_layout': {
      id: '/(docs)/_docs-layout/docs/_layout'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof docsDocsLayoutDocsLayoutRouteImport
      parentRoute: typeof docsDocsLayoutDocsRoute
    }
    '/(docs)/_docs-layout/docs/_layout/': {
      id: '/(docs)/_docs-layout/docs/_layout/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof docsDocsLayoutDocsLayoutIndexRouteImport
      parentRoute: typeof docsDocsLayoutDocsLayoutRoute
    }
    '/(dashboard)/dashboard/_dashboard-layout/settings/': {
      id: '/(dashboard)/dashboard/_dashboard-layout/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof dashboardDashboardDashboardLayoutSettingsIndexRouteImport
      parentRoute: typeof dashboardDashboardDashboardLayoutRoute
    }
    '/(dashboard)/dashboard/_dashboard-layout/billing/': {
      id: '/(dashboard)/dashboard/_dashboard-layout/billing/'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof dashboardDashboardDashboardLayoutBillingIndexRouteImport
      parentRoute: typeof dashboardDashboardDashboardLayoutRoute
    }
    '/(docs)/_docs-layout/docs/_layout/$': {
      id: '/(docs)/_docs-layout/docs/_layout/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof docsDocsLayoutDocsLayoutSplatRouteImport
      parentRoute: typeof docsDocsLayoutDocsLayoutRoute
    }
  }
}

interface authAuthLayoutRouteChildren {
  authAuthLayoutLoginIndexRoute: typeof authAuthLayoutLoginIndexRoute
  authAuthLayoutRegisterIndexRoute: typeof authAuthLayoutRegisterIndexRoute
}

const authAuthLayoutRouteChildren: authAuthLayoutRouteChildren = {
  authAuthLayoutLoginIndexRoute: authAuthLayoutLoginIndexRoute,
  authAuthLayoutRegisterIndexRoute: authAuthLayoutRegisterIndexRoute,
}

const authAuthLayoutRouteWithChildren = authAuthLayoutRoute._addFileChildren(
  authAuthLayoutRouteChildren,
)

interface docsDocsLayoutDocsLayoutRouteChildren {
  docsDocsLayoutDocsLayoutSplatRoute: typeof docsDocsLayoutDocsLayoutSplatRoute
  docsDocsLayoutDocsLayoutIndexRoute: typeof docsDocsLayoutDocsLayoutIndexRoute
}

const docsDocsLayoutDocsLayoutRouteChildren: docsDocsLayoutDocsLayoutRouteChildren =
  {
    docsDocsLayoutDocsLayoutSplatRoute: docsDocsLayoutDocsLayoutSplatRoute,
    docsDocsLayoutDocsLayoutIndexRoute: docsDocsLayoutDocsLayoutIndexRoute,
  }

const docsDocsLayoutDocsLayoutRouteWithChildren =
  docsDocsLayoutDocsLayoutRoute._addFileChildren(
    docsDocsLayoutDocsLayoutRouteChildren,
  )

interface docsDocsLayoutDocsRouteChildren {
  docsDocsLayoutDocsLayoutRoute: typeof docsDocsLayoutDocsLayoutRouteWithChildren
}

const docsDocsLayoutDocsRouteChildren: docsDocsLayoutDocsRouteChildren = {
  docsDocsLayoutDocsLayoutRoute: docsDocsLayoutDocsLayoutRouteWithChildren,
}

const docsDocsLayoutDocsRouteWithChildren =
  docsDocsLayoutDocsRoute._addFileChildren(docsDocsLayoutDocsRouteChildren)

interface docsDocsLayoutRouteChildren {
  docsDocsLayoutDocsRoute: typeof docsDocsLayoutDocsRouteWithChildren
  docsDocsLayoutGuidesIndexRoute: typeof docsDocsLayoutGuidesIndexRoute
}

const docsDocsLayoutRouteChildren: docsDocsLayoutRouteChildren = {
  docsDocsLayoutDocsRoute: docsDocsLayoutDocsRouteWithChildren,
  docsDocsLayoutGuidesIndexRoute: docsDocsLayoutGuidesIndexRoute,
}

const docsDocsLayoutRouteWithChildren = docsDocsLayoutRoute._addFileChildren(
  docsDocsLayoutRouteChildren,
)

interface editorEditorLayoutRouteChildren {
  editorEditorLayoutEditorPostIdRoute: typeof editorEditorLayoutEditorPostIdRoute
}

const editorEditorLayoutRouteChildren: editorEditorLayoutRouteChildren = {
  editorEditorLayoutEditorPostIdRoute: editorEditorLayoutEditorPostIdRoute,
}

const editorEditorLayoutRouteWithChildren =
  editorEditorLayoutRoute._addFileChildren(editorEditorLayoutRouteChildren)

interface marketingMarketingLayoutRouteChildren {
  marketingMarketingLayoutSlugRoute: typeof marketingMarketingLayoutSlugRoute
  marketingMarketingLayoutIndexRoute: typeof marketingMarketingLayoutIndexRoute
  marketingMarketingLayoutBlogSlugRoute: typeof marketingMarketingLayoutBlogSlugRoute
  marketingMarketingLayoutBlogIndexRoute: typeof marketingMarketingLayoutBlogIndexRoute
  marketingMarketingLayoutPricingIndexRoute: typeof marketingMarketingLayoutPricingIndexRoute
}

const marketingMarketingLayoutRouteChildren: marketingMarketingLayoutRouteChildren =
  {
    marketingMarketingLayoutSlugRoute: marketingMarketingLayoutSlugRoute,
    marketingMarketingLayoutIndexRoute: marketingMarketingLayoutIndexRoute,
    marketingMarketingLayoutBlogSlugRoute:
      marketingMarketingLayoutBlogSlugRoute,
    marketingMarketingLayoutBlogIndexRoute:
      marketingMarketingLayoutBlogIndexRoute,
    marketingMarketingLayoutPricingIndexRoute:
      marketingMarketingLayoutPricingIndexRoute,
  }

const marketingMarketingLayoutRouteWithChildren =
  marketingMarketingLayoutRoute._addFileChildren(
    marketingMarketingLayoutRouteChildren,
  )

interface dashboardDashboardDashboardLayoutRouteChildren {
  dashboardDashboardDashboardLayoutIndexRoute: typeof dashboardDashboardDashboardLayoutIndexRoute
  dashboardDashboardDashboardLayoutBillingIndexRoute: typeof dashboardDashboardDashboardLayoutBillingIndexRoute
  dashboardDashboardDashboardLayoutSettingsIndexRoute: typeof dashboardDashboardDashboardLayoutSettingsIndexRoute
}

const dashboardDashboardDashboardLayoutRouteChildren: dashboardDashboardDashboardLayoutRouteChildren =
  {
    dashboardDashboardDashboardLayoutIndexRoute:
      dashboardDashboardDashboardLayoutIndexRoute,
    dashboardDashboardDashboardLayoutBillingIndexRoute:
      dashboardDashboardDashboardLayoutBillingIndexRoute,
    dashboardDashboardDashboardLayoutSettingsIndexRoute:
      dashboardDashboardDashboardLayoutSettingsIndexRoute,
  }

const dashboardDashboardDashboardLayoutRouteWithChildren =
  dashboardDashboardDashboardLayoutRoute._addFileChildren(
    dashboardDashboardDashboardLayoutRouteChildren,
  )

interface dashboardDashboardRouteChildren {
  dashboardDashboardDashboardLayoutRoute: typeof dashboardDashboardDashboardLayoutRouteWithChildren
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardDashboardLayoutRoute:
    dashboardDashboardDashboardLayoutRouteWithChildren,
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authAuthLayoutRoute: authAuthLayoutRouteWithChildren,
  docsDocsLayoutRoute: docsDocsLayoutRouteWithChildren,
  editorEditorLayoutRoute: editorEditorLayoutRouteWithChildren,
  marketingMarketingLayoutRoute: marketingMarketingLayoutRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
